name: Tests with Puppeteer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  installDependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
        # with:
        #   args: install
      - run: npm ci
      - run: mkdir prod-materials && NODE_ENV=dev bash build.sh
      - name: Test Code
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: "true"
        with:
          args: npm test
